language: nodejs

before_script:
  - yarn run setup
  - yarn run compile

script:
  - yarn run test

after_sucess:
  - yarn run docs
  - npm pack

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN
    on:
      tags: true